[package]
name = "magic-mirror-app"
version = "2.0.0"
description = "A Tauri App for a Magic Mirror"
authors = ["stabbert"]
license = "MIT"
repository = "https://github.com/stabbert/magic-mirror"
default-run = "magic-mirror-app"
edition = "2021"
rust-version = "1.74.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.0", features = [] }

[dependencies]
openssl = { version = "0.10.61", features = ["vendored"] }
serde_json = "1.0.108"
serde = { version = "1.0.193", features = ["derive"] }
tauri = { version = "1.5.3", features = ["fs-read-file", "http-request", "path-all"] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]

[package.metadata.cross.target.arm-unknown-linux-gnueabihf]
# Install tauri dependencies see: https://github.com/cross-rs/cross#pre-build-hook
pre-build = ["apt-get update && apt-get install --assume-yes libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev libssl-dev"]

[package.metadata.cross.target.arm-unknown-linux-gnueabihf.env]
volumes = ["../dist"]
