name: Release

on:
  push:
    branches:
      - alpha
      - main
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.prettierrc.js'
      - 'eslint.config.js'

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          workspaces: './src-tauri -> target'

      - name: Build cross compiling Docker Image for ARMv8 Raspberry Pi Zero 2
        run: |
          cat > Dockerfile << \EOF      
          FROM debian:trixie-20260406-slim
          ARG DEBIAN_FRONTEND=noninteractive

          RUN apt-get update && \
              apt-get install --assume-yes --no-install-recommends \
                build-essential \
                ca-certificates \
                curl \
                gcc-aarch64-linux-gnu \
                pkg-config

          RUN dpkg --add-architecture arm64 && \
              apt-get update && apt-get install --assume-yes --no-install-recommends \
                libssl-dev:arm64 \
                libwebkit2gtk-4.1-dev:arm64

          # Install NodeJS
          RUN curl -fsSL https://deb.nodesource.com/setup_24.x | bash - &&\
            apt-get install --assume-yes --no-install-recommends nodejs

          # Install Rust
          RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain=1.95.0 -y --target aarch64-unknown-linux-gnu

          # Set environment variables
          ENV CARGO_INCREMENTAL=0 \
            CARGO_PROFILE_TEST_DEBUG=0 \
            CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc \
            PATH="/root/.cargo/bin:$PATH" \
            PKG_CONFIG_PATH="/usr/lib/aarch64-linux-gnu/pkgconfig/:${PKG_CONFIG_PATH}" \
            PKG_CONFIG_SYSROOT_DIR=/usr/aarch64-linux-gnu \
            RUSTFLAGS="-C target-cpu=cortex-a53"

          WORKDIR /app
          EOF
          
          docker build --tag debian/tauri-cross:aarch64-linux-gnu .

      - name: Configure semantic release
        run: |
          cat > .releaserc.json << \EOF
          {
            "plugins": [
              "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              ["@semantic-release/exec", {
                "prepareCmd": "sed -i 's/\"version\": \"[^\"]*\"/\"version\": \"${nextRelease.version}\"/' src-tauri/tauri.conf.json",
                "publishCmd": "docker run --rm -i -v $PWD:/app debian/tauri-cross:aarch64-linux-gnu bash -c 'npm ci && npm run tauri build -- --config src-tauri/tauri.prod.conf.json --target aarch64-unknown-linux-gnu'"
              }],
              ["@semantic-release/git", {
                "assets": ["src-tauri/tauri.conf.json"]
              }],
              ["@semantic-release/github", {
                "assets": [
                  {"path": "src-tauri/target/aarch64-unknown-linux-gnu/release/bundle/deb/*.deb"}
                ],
                "failComment": false,
                "labels": false,
                "releaseLabels": false,
                "successCommentCondition": false
              }]
            ]
          }
          EOF

      - name: Create semantic version
        uses: cycjimmy/semantic-release-action@v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: | # Documentation for branch configuration https://semantic-release.gitbook.io/semantic-release/usage/configuration#branches
            [
              '+([0-9])?(.{+([0-9]),x}).x', 
              'main', 
              { "name": "alpha", "prerelease": true }
            ]
          extra_plugins: |
            @semantic-release/commit-analyzer@v13.0.1
            @semantic-release/exec@v7.1.0
            @semantic-release/git@v10.0.1
            @semantic-release/github@v12.0.6
            @semantic-release/release-notes-generator@v14.1.0
          semantic_version: v25.0.3
