name: Release

on:
  push:
    branches:
      - main
      - completely_rework

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          workspaces: './src-tauri -> target'

      - name: Build deb bundle with docker and cross compiling for ARMv6 raspberry pi zero
        run: |
          cat <<EOF > Dockerfile       
          FROM balenalib/rpi-raspbian:bookworm-20230705
          ARG DEBIAN_FRONTEND=noninteractive

          RUN apt-get update && \
              apt-get install --assume-yes --no-install-recommends \
                libwebkit2gtk-4.1

          # Install NodeJS
          RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - &&\
            apt-get install --assume-yes --no-install-recommends nodejs

          # Install Rust
          RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain=1.88.0 -y --target arm-unknown-linux-gnueabihf

          # Set envs
          ENV CARGO_INCREMENTAL=0 \
            CARGO_PROFILE_TEST_DEBUG=0 \
            CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc \
            PATH="/root/.cargo/bin:$PATH" \
            PKG_CONFIG_PATH="/usr/lib/arm-linux-gnueabihf/pkgconfig/:${PKG_CONFIG_PATH}" \
            PKG_CONFIG_SYSROOT_DIR=/usr/arm-linux-gnueabihf/

          WORKDIR /app
          EOF

          docker build --tag debian/tauri-cross:arm-unknown-linux-gnueabihf .

          docker run --rm -i -v $PWD:/app \
            debian/tauri-cross:arm-unknown-linux-gnueabihf bash \
            -c "npm ci && npm run tauri build -- --config src-tauri/tauri.prod.conf.json --target arm-unknown-linux-gnueabihf"

      - name: Get app version
        run: echo "APP_VERSION=$(jq -r .version src-tauri/tauri.conf.json)" >> $GITHUB_ENV

      - name: Upload deb bundle
        uses: actions/upload-artifact@v4
        with:
          name: Debian ARMv6 Raspberry Pi Zero Bundle
          path: ./src-tauri/target/arm-unknown-linux-gnueabihf/release/bundle/deb/magic-mirror_${{ env.APP_VERSION }}_armhf.deb
